version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  discoveryserver:
    build: ./discoveryserver
    container_name: discoveryserver
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
      - spring.data.mongodb.uri=mongodb://mongodb:27017/authdb
      - eureka.client.service-url.defaultZone=http://discoveryserver:8761/eureka
    depends_on:
      discoveryserver:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - microservice-network

  productservice:
    build: ./productservice
    container_name: productservice
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
      - spring.data.mongodb.uri=mongodb://mongodb:27017/product
      - eureka.client.service-url.defaultZone=http://discoveryserver:8761/eureka
    depends_on:
      discoveryserver:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - microservice-network

  apigateway:
    build: ./apigateway
    container_name: apigateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
      - eureka.client.service-url.defaultZone=http://discoveryserver:8761/eureka
    depends_on:
      discoveryserver:
        condition: service_healthy
      auth-service:
        condition: service_started
      productservice:
        condition: service_started
    networks:
      - microservice-network

volumes:
  mongodb_data:

networks:
  microservice-network:
    driver: bridge 