version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservice-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservice-network

  discoveryserver:
    build: ./discoveryserver
    container_name: discoveryserver
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=discoveryserver
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false
      - EUREKA_SERVER_WAIT_TIME_IN_MS_WHEN_SYNC_EMPTY=0
      - EUREKA_SERVER_RENEWAL_PERCENT_THRESHOLD=0.85
      - SERVER_PORT=8761
    networks:
      - microservice-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
      - spring.data.mongodb.uri=mongodb://mongodb:27017/authdb
      - spring.data.redis.host=redis
      - spring.data.redis.port=6379
      - eureka.client.service-url.defaultZone=http://discoveryserver:8761/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=auth-service
      - EUREKA_CLIENT_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10
      - SERVER_PORT=8081
    networks:
      - microservice-network
    depends_on:
      - discoveryserver
      - mongodb
      - redis

  productservice:
    build: ./productservice
    container_name: productservice
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
      - spring.data.mongodb.uri=mongodb://mongodb:27017/product
      - eureka.client.service-url.defaultZone=http://discoveryserver:8761/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=productservice
      - EUREKA_CLIENT_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10
      - SERVER_PORT=8082
    networks:
      - microservice-network
    depends_on:
      - discoveryserver
      - mongodb

  apigateway:
    build: ./apigateway
    container_name: apigateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
      - eureka.client.service-url.defaultZone=http://discoveryserver:8761/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=apigateway
      - EUREKA_CLIENT_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10
      - SERVER_PORT=8080
    networks:
      - microservice-network
    depends_on:
      - discoveryserver
      - auth-service
      - productservice

volumes:
  mongodb_data:

networks:
  microservice-network:
    driver: bridge
